---
id: mroonga-introduction
base_name: mroonga-introduction
tags:
- rabbit
- mroonga
- mysql
- mariadb
presentation_date: 
version: 2016.12.26.1
licenses:
- CC-BY-SA-4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: クリアコード
  email: rubygems@clear-code.com
  rubygems_user: clear-code
  slideshare_user: 
  speaker_deck_user: 
